default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: shoply_dev

test:
  <<: *default
  database: shoply_test

# production:
#   <<: *default
#   database: shoply_prod
